version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10.0
    working_directory: ~/repo

  yarn_cache_config: &yarn_cache_config
    key: dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
    paths:
      - node_modules

  yarn_restore_cache: &yarn_restore_cache
    restore_cache:
      <<: *yarn_cache_config
      name: Restore yarn cache

  yarn_save_cache: &yarn_save_cache
    save_cache:
      <<: *yarn_cache_config
      name: Save yarn cache

  deps: &deps
    run:
      name: Install dependencies
      command: yarn install

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - *yarn_restore_cache
      - *deps
      - *yarn_save_cache
      - run:
          name: Test
          command: yarn test
